language: c

jobs:
  include:
    # Ubuntu Focal (20.04) with GCC 9.3 on big-endian
    - os: linux
      arch: s390x
      dist: focal
      addons:
        apt:
          packages:
            - meson
            - check

    # Ubuntu Bionic (18.04) with GCC 7
    - os: linux
      dist: bionic
      addons:
        apt:
          sources:
            - sourceline: 'ppa:deadsnakes/ppa' # for Python 3.7 (required by Meson)
          packages:
            - python3.6
            - python3-urllib3
            - ninja-build
            - check
      before_install:
        - wget https://bootstrap.pypa.io/get-pip.py
        - /usr/bin/python3.6 get-pip.py --user
      install:
        - /usr/bin/python3.6 $HOME/.local/bin/pip install --user meson

    - os: osx
      osx_image: xcode11.6
      addons:
        homebrew:
          packages:
            - ccache
            - meson
            - ninja
            - check

cache:
  apt: true
  ccache: true
  directories:
    - $HOME/Library/Caches/Homebrew

before_cache:
  - test "$TRAVIS_OS_NAME" != "osx" || brew cleanup

before_install:
  - test "$TRAVIS_OS_NAME" != "linux" || export PATH="$HOME/.local/bin:$PATH"
  - test "$TRAVIS_OS_NAME" != "osx" || export PATH="/usr/local/opt/ccache/libexec:$PATH"
  - test "$TRAVIS_OS_NAME" != "osx" || export HOMEBREW_NO_ANALYTICS=1

install:

before_script:
  - ccache -s

script:
  - OPTIONS="-Dtest=true"
  - meson . output $OPTIONS
  - ninja -v -C output test
  - ccache -s
